version: "3.0"
networks:
  app-shared:
    driver: bridge

services:

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq_general
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    networks:
      - app-shared