version: '3'

networks:
  auth:
  general_app-shared:
    external: true

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_auth
    ports:
      - "8082:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - auth

  mysql:
    image: mysql:5.7.29
    container_name: mysql_auth
    hostname: "mysql"
    restart: unless-stopped
    tty: true
    ports:
      - "33062:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - auth

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_auth
    volumes:
      - ./src:/var/www/html
    ports:
      - "9002:9000"
    networks:
      - auth
      - general_app-shared

  composer:
    image: composer:latest
    container_name: composer_two
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - auth

  npm:
    image: node:13.7
    container_name: npm_auth
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan_auth
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - auth
      - general_app-shared

volumes:
  mysql_data:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}"
